spring:
  application:
    name: api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8765