spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/google_books
    url: jdbc:postgresql://host.docker.internal:5432/google_books
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: google-books-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.99:8761/eureka
server:
  port: 8092
