spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/book
    username: root
    password: 12345678
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: book-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka