server:
  port: 8190
spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/issue
    username: root
    password: 12345678
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: issue-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka