spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/persons
#    url: jdbc:postgresql://host.docker.internal:5432/persons
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: person-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.99:8761/eureka
server:
  port: 8082